from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.conf import settings
from django.db.models import Q, Count
from .models import JournalEntry, Blurb, Report, Goal, Tag
import json
from .forms import JournalForm, AskJournalForm, GoalForm
from datetime import datetime, timedelta
from django.utils import timezone
import requests
from collections import Counter
import calendar
from django.core.paginator import Paginator
# Create your views here.


# Simple helper function:
mood_colors = {
    "happy": "badge-primary",
    "sad": "badge-secondary",
    "angry": "badge-danger",
    "afraid": "badge-warning",
    "excited": "badge-success",
    "calm": "badge-info",
    "worried": "badge-light",
    "in love": "badge-danger",
    "surprised": "badge-warning",
    "proud": "badge-success",
    "ashamed": "badge-secondary",
    "frustrated": "badge-danger",
    "guilty": "badge-danger",
    "curious": "badge-info",
    "nostalgic": "badge-light",
    "hopeful": "badge-primary",
    "disappointed": "badge-secondary",
    "embarrassed": "badge-secondary",
    "envious": "badge-danger",
    "grateful": "badge-success",
    "longing": "badge-info",
    "relieved": "badge-primary",
    "optimistic": "badge-primary",
    "pessimistic": "badge-dark"
}

# CSS color mapping for mood calendar heatmap
mood_heatmap_colors = {
    "happy": "#28a745",
    "sad": "#6c757d",
    "angry": "#dc3545",
    "afraid": "#ffc107",
    "excited": "#28a745",
    "calm": "#17a2b8",
    "worried": "#f8f9fa",
    "in love": "#dc3545",
    "surprised": "#ffc107",
    "proud": "#28a745",
    "ashamed": "#6c757d",
    "frustrated": "#dc3545",
    "guilty": "#dc3545",
    "curious": "#17a2b8",
    "nostalgic": "#f8f9fa",
    "hopeful": "#007bff",
    "disappointed": "#6c757d",
    "embarrassed": "#6c757d",
    "envious": "#dc3545",
    "grateful": "#28a745",
    "longing": "#17a2b8",
    "relieved": "#007bff",
    "optimistic": "#007bff",
    "pessimistic": "#343a40"
}


def mood_list_creation(entry: JournalEntry):
    return_list = []
    if(entry.mood is None):
        return ['<span class="badge badge-pill badge-light">Journal is yet to be processed by AI</span>']
    else:
        # We expect that entry.mood is a valid python array
        try:
            # Hacky way of doing this, but, this is the best I can think of
            #print(json.loads(entry.mood.replace("'", '"'))) # AI will generate the list with either ' or ", this fixes it
            moodl = json.loads(entry.mood.replace("'", '"'))
            for element in moodl:
                #print(element)
                if mood_colors.get(element) is not None:
                    return_list.append(f'<span class="badge badge-pill {mood_colors.get(element)}">{element}</span>')
        except:
           return ['<span class="badge badge-pill badge-danger">Mood list generated by AI is invalid</span>']
    #print(return_list)
    return return_list


def calculate_current_streak(entries):
    """Calculate current journaling streak (consecutive days ending today or yesterday)."""
    if not entries:
        return 0
    dates = sorted(set(entries.values_list('date', flat=True)), reverse=True)
    today = timezone.now().date()
    yesterday = today - timedelta(days=1)
    # Streak must start from today or yesterday
    if dates[0] not in (today, yesterday):
        return 0
    streak = 1
    for i in range(1, len(dates)):
        if dates[i-1] - dates[i] == timedelta(days=1):
            streak += 1
        else:
            break
    return streak


def calculate_longest_streak(entries):
    """Calculate longest journaling streak ever."""
    if not entries:
        return 0
    dates = sorted(set(entries.values_list('date', flat=True)))
    longest = 1
    current = 1
    for i in range(1, len(dates)):
        if dates[i] - dates[i-1] == timedelta(days=1):
            current += 1
            longest = max(longest, current)
        else:
            current = 1
    return longest


def get_most_common_mood(entries):
    """Get the most common mood from all journal entries."""
    all_moods = []
    for entry in entries:
        if entry.mood:
            try:
                moods = json.loads(entry.mood.replace("'", '"'))
                all_moods.extend(moods)
            except (json.JSONDecodeError, AttributeError):
                pass
    if not all_moods:
        return None
    counter = Counter(all_moods)
    return counter.most_common(1)[0][0]


def generate_calendar_data(earliest, latest, mood_map, date_entry_map=None, mood_colors=None):
    """Generate month-by-month calendar data."""
    from datetime import date
    months = []
    current = date(earliest.year, earliest.month, 1)
    end = date(latest.year, latest.month, 1)

    while current <= end:
        month_cal = calendar.monthcalendar(current.year, current.month)
        days = []
        for week in month_cal:
            for day_num in week:
                if day_num == 0:
                    days.append(None)  # Empty cell
                else:
                    d = date(current.year, current.month, day_num)
                    mood = mood_map.get(d.isoformat())
                    days.append({
                        'day': day_num,
                        'date': d,
                        'date_str': d.isoformat(),
                        'mood': mood,
                        'mood_color': mood_colors.get(mood, '#e9ecef') if mood and mood_colors else '#e9ecef',
                        'entry_id': date_entry_map.get(d.isoformat()) if date_entry_map else None,
                    })
        months.append({
            'month': current.strftime('%B %Y'),
            'days': days,
        })
        # Advance to next month
        if current.month == 12:
            current = date(current.year + 1, 1, 1)
        else:
            current = date(current.year, current.month + 1, 1)

    return months


@login_required
def dashboard(request):
    entries = JournalEntry.objects.filter(user=request.user).order_by('-date')
    total_entries = entries.count()
    current_streak = calculate_current_streak(entries)
    longest_streak = calculate_longest_streak(entries)
    most_common_mood = get_most_common_mood(entries)
    recent_entries = entries[:5]

    # Get bookmarked entries for quick access
    bookmarked = entries.filter(bookmarked=True)[:5]

    context = {
        'total_entries': total_entries,
        'current_streak': current_streak,
        'longest_streak': longest_streak,
        'most_common_mood': most_common_mood,
        'recent_entries': recent_entries,
        'bookmarked_entries': bookmarked,
        'use_ai': settings.USE_AI,
    }
    return render(request, 'dashboard.html', context)


@login_required
def journals(request):
    entries = JournalEntry.objects.filter(user=request.user)

    # Search
    query = request.GET.get('q', '').strip()
    if query:
        entries = entries.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(reflections__icontains=query) |
            Q(gratitude__icontains=query)
        )

    # Filter by mood
    mood_filter = request.GET.get('mood', '').strip()
    if mood_filter:
        entries = entries.filter(mood__icontains=mood_filter)

    # Filter by date range
    date_from = request.GET.get('date_from', '').strip()
    date_to = request.GET.get('date_to', '').strip()
    if date_from:
        entries = entries.filter(date__gte=date_from)
    if date_to:
        entries = entries.filter(date__lte=date_to)

    # Filter by tag
    tag_filter = request.GET.get('tag', '').strip()
    if tag_filter:
        entries = entries.filter(tags__name__iexact=tag_filter)

    entries = entries.order_by('-date')

    # Get all unique moods for filter dropdown
    all_moods = set()
    for entry in JournalEntry.objects.filter(user=request.user):
        if entry.mood:
            try:
                moods = json.loads(entry.mood.replace("'", '"'))
                all_moods.update(moods)
            except (json.JSONDecodeError, AttributeError):
                pass

    # Get all tags for filter dropdown
    all_tags = Tag.objects.filter(journal_entries__user=request.user).distinct()

    # Pagination
    paginator = Paginator(entries, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'journalindex.html', {
        'page_obj': page_obj,
        'journal_entries': page_obj,
        'use_ai': settings.USE_AI,
        'query': query,
        'mood_filter': mood_filter,
        'date_from': date_from,
        'date_to': date_to,
        'tag_filter': tag_filter,
        'all_moods': sorted(all_moods),
        'all_tags': all_tags,
    })


def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/')
        else:
            return render(request, 'login.html', {'error': 'Invalid credentials'})
    return render(request, 'login.html')


@login_required
def journal_question(request):
    if not settings.USE_AI:
        return HttpResponseRedirect("/journals/")
    if request.method == "POST":
        form = AskJournalForm(request.POST, user=request.user)
        # This is a neat little trick, if we call it this way, it'll create it in memory but not persist to the database
        if form.is_valid():
            # Now, this is the step where we collate the question, journals, send to the AI, and display the response
            # Step 1: Collate the question and journals.
            prompt=f"You are an unbiased AI agent who has been given the task of answering a query from a user. The qeury from the user will require you to consider one or more journal entries, some of which will be relevant (important! not all journal entries may be relevant.) Your task is to answer the question of the user as best as you can while considering these journals. Where plausible, cite the journals in your answer if they are relevant.\n Format your response in markdown."
            question=f"\nNow, consider the question from the user:\n```{form.cleaned_data['question']}```\n"
            journal_preamble=f"Now, consider the following journal entries.\n"
            for journal in form.cleaned_data['journals']:
                journal_preamble+=f"Journal Entry:\nDate: {journal.date}\nContent:\n```{journal.content}```"
            response = requests.post(settings.OLLAMA_API_URL, json={'model': settings.OLLAMA_MODEL, 'stream': False, 'options': {'num_ctx': 4096}, 'prompt': prompt + question + journal_preamble})
            return render(request, 'report_detail.html', {'report_entry' : Report(user=request.user, title='Temporary Question', type='w', content=response.json()['response'].split('</think>')[1].strip()) })
        # This isn't nice, but, I see no better option. TODO to add some more verbose error reporting.
        return HttpResponseRedirect("/journals/")
    else:
        form = AskJournalForm(user=request.user)
        return render(request, 'journal_ask.html', {'form': form})


@login_required
def journal_detail(request, id):
    entry = get_object_or_404(JournalEntry, id=id, user=request.user)
    mood = mood_list_creation(entry)
    tags = entry.tags.all()
    return render(request, 'journal_detail.html', {'entry': entry, 'moods' : mood, 'tags': tags})


@login_required
def journal_create(request):
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = JournalForm(request.POST, use_ai=settings.USE_AI)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            new = JournalEntry()
            new.content = form.cleaned_data['content']
            if len(form.cleaned_data['reflections']) > 5:
                new.reflections = form.cleaned_data['reflections']
            if len(form.cleaned_data['gratitude']) > 5:
                new.gratitude = form.cleaned_data['gratitude']
            new.user =  request.user # This WILL error when not logged in, but, that's fine
            # When AI is disabled, set title to date/time format
            if not settings.USE_AI:
                new.title = f"Journal Entry - {timezone.now().strftime('%Y-%m-%d %H:%M')}"
                # Set mood from keyword selection
                mood_selection = form.cleaned_data.get('mood')
                if mood_selection:
                    new.mood = json.dumps(mood_selection)
            new.save()
            # Handle tags
            tags_str = form.cleaned_data.get('tags', '')
            if tags_str:
                tag_names = [t.strip() for t in tags_str.split(',') if t.strip()]
                for tag_name in tag_names:
                    tag, created = Tag.objects.get_or_create(user=request.user, name=tag_name.lower())
                    new.tags.add(tag)
            # Let's mark the blurbs as spent now
            # Note this has a known issue - if the blurb was sent after the user started journaling
            # but before it was submitted, it would be marked as spent. This is not a big deal.
            for blurb in Blurb.objects.filter(user=request.user, journalEntry=None):
                blurb.journalEntry = new
                blurb.save()
            # redirect to a new URL:
            return HttpResponseRedirect("/journals/")
        return render(request, 'journal_submit.html', {'form':form})
    else:
        form = JournalForm(use_ai=settings.USE_AI)
        blurbs = list(Blurb.objects.filter(user=request.user, journalEntry=None))
        return render(request, 'journal_submit.html', {'form':form, 'blurbs' : blurbs})


@login_required
def journal_edit(request, id):
    entry = get_object_or_404(JournalEntry, id=id, user=request.user)
    if request.method == "POST":
        form = JournalForm(request.POST, instance=entry, use_ai=settings.USE_AI)
        if form.is_valid():
            form.save()
            if not settings.USE_AI:
                # Update title if it was auto-generated
                if entry.title and entry.title.startswith("Journal Entry -"):
                    entry.title = f"Journal Entry - {timezone.now().strftime('%Y-%m-%d %H:%M')}"
                mood_selection = form.cleaned_data.get('mood')
                if mood_selection:
                    entry.mood = json.dumps(mood_selection)
                    entry.save()
            # Handle tags
            tags_str = form.cleaned_data.get('tags', '')
            entry.tags.clear()
            if tags_str:
                tag_names = [t.strip() for t in tags_str.split(',') if t.strip()]
                for tag_name in tag_names:
                    tag, created = Tag.objects.get_or_create(user=request.user, name=tag_name.lower())
                    entry.tags.add(tag)
            return HttpResponseRedirect(f"/details/{id}/")
        return render(request, 'journal_edit.html', {'form': form, 'entry': entry})
    else:
        form = JournalForm(instance=entry, use_ai=settings.USE_AI)
        # Pre-fill tags field
        existing_tags = ', '.join(t.name for t in entry.tags.all())
        return render(request, 'journal_edit.html', {'form': form, 'entry': entry, 'existing_tags': existing_tags})


@login_required
def journal_delete(request, id):
    entry = get_object_or_404(JournalEntry, id=id, user=request.user)
    if request.method == "POST":
        entry.delete()
        return HttpResponseRedirect("/journals/")
    return render(request, 'journal_confirm_delete.html', {'entry': entry})


@login_required
def journal_toggle_bookmark(request, id):
    """Toggle bookmark status for a journal entry."""
    entry = get_object_or_404(JournalEntry, id=id, user=request.user)
    entry.bookmarked = not entry.bookmarked
    entry.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/journals/'))


@login_required
def report_list(request):
    """List all reports for the current user."""
    reports = Report.objects.filter(user=request.user).order_by('-id')
    paginator = Paginator(reports, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'report_list.html', {'reports': page_obj, 'page_obj': page_obj})


@login_required
def report_detail(request, id):
    report_entry = get_object_or_404(Report, id=id, user=request.user)
    return render(request, 'report_detail.html', {'report_entry' : report_entry})


@login_required
def goals(request):
    goal_entries = Goal.objects.filter(user=request.user).order_by('-created_at')
    paginator = Paginator(goal_entries, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'goalindex.html', {'goal_entries': page_obj, 'page_obj': page_obj})


#    path('goals/create.html', views.goals_create, name='goals_create'),
@login_required
def goal_create(request):
    goal_entries = Goal.objects.filter(user=request.user).order_by('-created_at')
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = GoalForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            new = Goal()
            new.user = request.user # This WILL error when not logged in, but, that's fine
            # {'goal_title': 'Test', 'goal_text': 'test', 'goal_rationale': 'test', 'length': '1m', 'parent_goal': None}
            new.goal_title = form.cleaned_data['goal_title']
            new.goal_text = form.cleaned_data['goal_text']
            new.goal_rationale = form.cleaned_data['goal_rationale']
            new.length = form.cleaned_data['length']
            new.progress = form.cleaned_data.get('progress') or 0
            if form.cleaned_data['parent_goal']:
                new.parent_goal = form.cleaned_data['parent_goal']
            # redirect to a new URL:
            new.save()
            return HttpResponseRedirect("/goals/")
        return render(request, 'goal_submit.html', {'form':form})
    else:
        form = GoalForm()
        return render(request, 'goal_submit.html', {'form':form, 'goals' : goal_entries})


#    path('goals/<int:id>/', views.goals_detail, name='goals_detail'),
@login_required
def goal_detail(request, id):
    goal_entry = get_object_or_404(Goal, id=id, user=request.user)
    today = timezone.now()
    expiration_date = goal_entry.created_at

    # Terrible way to do this, but, we'll decompose the options to a list eventually
    # XXX: Define this as a list with constants that are pulled out of the models file
    if goal_entry.length == '1m':
        expiration_date += timedelta(days=30)
    elif goal_entry.length == '6m':
        expiration_date += timedelta(days=180)
    elif goal_entry.length == '1y':
        expiration_date += timedelta(days=365)
    elif goal_entry.length == '5y':
        expiration_date += timedelta(days=1825)

    if today > expiration_date:
        expired = True
        remaining_time = None
        expiration_date_str = expiration_date.strftime('%Y-%m-%d')
    else:
        expired = False
        remaining_time = (expiration_date - today).days
        expiration_date_str = expiration_date.strftime('%Y-%m-%d')

    return render(request, 'goal_detail.html', {'goal' : goal_entry, 'expired': expired, 'remaining_time': remaining_time, 'expiration_date_str': expiration_date_str,})


@login_required
def goal_edit(request, id):
    goal_entry = get_object_or_404(Goal, id=id, user=request.user)
    if request.method == "POST":
        form = GoalForm(request.POST, instance=goal_entry)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect("/goals/")
        return render(request, 'goal_edit.html', {'form': form, 'goal': goal_entry})
    else:
        form = GoalForm(instance=goal_entry)
        return render(request, 'goal_edit.html', {'form': form, 'goal': goal_entry})


@login_required
def goal_delete(request, id):
    goal_entry = get_object_or_404(Goal, id=id, user=request.user)
    if request.method == "POST":
        goal_entry.delete()
        return HttpResponseRedirect("/goals/")
    return render(request, 'goal_confirm_delete.html', {'goal': goal_entry})


@login_required
def mood_calendar(request):
    entries = JournalEntry.objects.filter(user=request.user).exclude(mood__isnull=True)

    # Build a dict of date -> primary mood
    mood_map = {}
    # Also build date -> entry id mapping for clickable cells
    date_entry_map = {}
    for entry in entries:
        if entry.mood:
            try:
                moods = json.loads(entry.mood.replace("'", '"'))
                if moods:
                    mood_map[entry.date.isoformat()] = moods[0]  # Primary mood
                    date_entry_map[entry.date.isoformat()] = entry.id
            except (json.JSONDecodeError, AttributeError):
                pass

    # Get date range
    if entries.exists():
        earliest = entries.order_by('date').first().date
        latest = entries.order_by('-date').first().date
    else:
        earliest = latest = timezone.now().date()

    # Generate calendar data
    calendar_months = generate_calendar_data(earliest, latest, mood_map, date_entry_map, mood_heatmap_colors)

    return render(request, 'mood_calendar.html', {
        'mood_map': json.dumps(mood_map),
        'earliest': earliest,
        'latest': latest,
        'mood_colors': mood_heatmap_colors,
        'calendar_months': calendar_months,
        'date_entry_map': date_entry_map,
    })


@login_required
def tag_list(request):
    """List all tags for the current user."""
    tags = Tag.objects.filter(user=request.user).annotate(
        entry_count=Count('journal_entries')
    ).order_by('name')
    paginator = Paginator(tags, 20)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'tag_list.html', {'tags': page_obj, 'page_obj': page_obj})


@login_required
def tag_detail(request, id):
    """Show all journal entries for a specific tag."""
    tag = get_object_or_404(Tag, id=id, user=request.user)
    entries = tag.journal_entries.filter(user=request.user).order_by('-date')
    paginator = Paginator(entries, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'tag_detail.html', {'tag': tag, 'entries': page_obj, 'page_obj': page_obj})


@login_required
def export_journals(request):
    """Export all journal entries as JSON or Markdown."""
    format_type = request.GET.get('format', 'json')
    entries = JournalEntry.objects.filter(user=request.user).order_by('date')

    if format_type == 'markdown':
        md_content = f"# Journal Export - {timezone.now().strftime('%Y-%m-%d')}\n\n"
        md_content += f"Total entries: {entries.count()}\n\n---\n\n"
        for entry in entries:
            md_content += f"## {entry.title or f'Journal Entry - {entry.date}'}\n\n"
            md_content += f"**Date:** {entry.date}\n\n"
            if entry.mood:
                md_content += f"**Mood:** {entry.mood}\n\n"
            md_content += f"### Content\n\n{entry.content or ''}\n\n"
            if entry.reflections:
                md_content += f"### Reflections\n\n{entry.reflections}\n\n"
            if entry.gratitude:
                md_content += f"### Gratitude\n\n{entry.gratitude}\n\n"
            tags = list(entry.tags.all())
            if tags:
                md_content += f"**Tags:** {', '.join(t.name for t in tags)}\n\n"
            md_content += "---\n\n"

        response = HttpResponse(md_content, content_type='text/markdown')
        response['Content-Disposition'] = f'attachment; filename="journals-{timezone.now().strftime("%Y-%m-%d")}.md"'
        return response
    else:
        data = []
        for entry in entries:
            entry_data = {
                'title': entry.title,
                'date': entry.date.isoformat(),
                'content': entry.content,
                'mood': entry.mood,
                'reflections': entry.reflections,
                'gratitude': entry.gratitude,
                'created_at': entry.created_at.isoformat(),
                'updated_at': entry.updated_at.isoformat(),
                'bookmarked': entry.bookmarked,
                'tags': [t.name for t in entry.tags.all()],
            }
            data.append(entry_data)

        response = HttpResponse(json.dumps(data, indent=2), content_type='application/json')
        response['Content-Disposition'] = f'attachment; filename="journals-{timezone.now().strftime("%Y-%m-%d")}.json"'
        return response


@login_required
def streak_detail(request):
    """Display detailed streak information."""
    entries = JournalEntry.objects.filter(user=request.user)

    dates = sorted(set(entries.values_list('date', flat=True)))

    streaks = []
    if dates:
        current_start = dates[0]
        current_end = dates[0]
        for i in range(1, len(dates)):
            if dates[i] - dates[i-1] == timedelta(days=1):
                current_end = dates[i]
            else:
                streaks.append({
                    'start': current_start,
                    'end': current_end,
                    'length': (current_end - current_start).days + 1,
                })
                current_start = dates[i]
                current_end = dates[i]
        streaks.append({
            'start': current_start,
            'end': current_end,
            'length': (current_end - current_start).days + 1,
        })

    streaks.sort(key=lambda s: s['length'], reverse=True)

    current_streak = calculate_current_streak(entries)
    longest_streak = max((s['length'] for s in streaks), default=0)
    total_days = len(dates)

    return render(request, 'streak_detail.html', {
        'streaks': streaks[:10],
        'current_streak': current_streak,
        'longest_streak': longest_streak,
        'total_days': total_days,
    })


@login_required
def profile(request):
    """Display user profile information."""
    return render(request, 'profile.html', {
        'user': request.user,
    })
