# Generated by Django 6.0.3 on 2026-04-01 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=1024, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('mood', models.CharField(blank=True, max_length=512, null=True)),
                ('reflections', models.TextField(blank=True, null=True)),
                ('gratitude', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Journal Entries',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(max_length=256)),
                ('goal_text', models.CharField(max_length=1024)),
                ('goal_rationale', models.CharField(max_length=1024)),
                ('goalCreated', models.DateTimeField()),
                ('length', models.CharField(choices=[('1m', '1 Month'), ('6m', '6 Months'), ('1y', '1 Year'), ('5y', '5 Years')], default='1m', max_length=2)),
                ('parent_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journalmain.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('journals', models.ManyToManyField(blank=True, to='journalmain.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='Blurb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurb_text', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('journalEntry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='journalmain.journalentry')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('type', models.CharField(choices=[('w', '1 Week'), ('m', '1 Month'), ('6', '6 Months'), ('y', '1 Year')], default='w', max_length=1)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='journalentry',
            name='month_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='month_report', to='journalmain.report'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='week_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='week_report', to='journalmain.report'),
        ),
    ]
