# Generated by Django 6.0.3 on 2026-04-01 20:50

from django.db import migrations


def populate_default_templates(apps, schema_editor):
    JournalTemplate = apps.get_model('journalmain', 'JournalTemplate')
    
    templates = [
        {
            'name': 'Daily Reflection',
            'description': 'Standard journaling with reflections and gratitude',
            'content_template': 'What happened today?\n\n{reflections}\n\nWhat are you grateful for today?\n\n{gratitude}',
            'order': 1,
        },
        {
            'name': 'Gratitude Journal',
            'description': 'Focus on things you are grateful for',
            'content_template': 'Three things I am grateful for today:\n\n1. \n2. \n3. \n\nWhy do these things matter to me?\n\n{gratitude}',
            'order': 2,
        },
        {
            'name': 'Weekly Review',
            'description': 'What went well, what did not, what to improve',
            'content_template': 'What went well this week?\n\n\nWhat did not go well?\n\n\nWhat can I improve next week?\n\n{reflections}\n\nWhat am I grateful for this week?\n\n{gratitude}',
            'order': 3,
        },
        {
            'name': 'Goal Check-in',
            'description': 'Progress on goals, obstacles, next steps',
            'content_template': 'What progress have I made on my goals this week?\n\n\nWhat obstacles did I encounter?\n\n\nWhat are my next steps?\n\n{reflections}',
            'order': 4,
        },
    ]
    
    for template_data in templates:
        JournalTemplate.objects.create(**template_data)


def remove_default_templates(apps, schema_editor):
    JournalTemplate = apps.get_model('journalmain', 'JournalTemplate')
    JournalTemplate.objects.filter(
        name__in=['Daily Reflection', 'Gratitude Journal', 'Weekly Review', 'Goal Check-in']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('journalmain', '0005_journaltemplate'),
    ]

    operations = [
        migrations.RunPython(populate_default_templates, remove_default_templates),
    ]
