# Generated by Django 6.0.3 on 2026-04-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalmain', '0006_populate_default_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='journals',
            field=models.ManyToManyField(blank=True, related_name='goals', to='journalmain.journalentry'),
        ),
    ]
