# Generated by Django 6.0.3 on 2026-04-05 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journalmain', '0007_alter_goal_journals'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestions', models.TextField()),
                ('tone', models.CharField(default='reflective', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='journalmain.journalentry')),
            ],
            options={
                'verbose_name_plural': 'Journal Feedback',
            },
        ),
    ]
